#!/bin/bash
set -euo pipefail

# SkVM Environment Binding Script
# Auto-generated by compiler Pass 2

log() { echo "[env-bind] $*"; }
warn() { echo "[env-bind] WARNING: $*" >&2; }

OS_NAME="$(uname -s | tr '[:upper:]' '[:lower:]' || echo unknown)"

prefer_python_cmd() {
  if [ -n "${CONDA_DEFAULT_ENV:-}" ]; then
    echo "python"
    return
  fi

  if [ -n "${VIRTUAL_ENV:-}" ]; then
    echo "python"
    return
  fi

  # macOS policy: prefer virtual envs, fallback to system python when unavailable.
  if [ "$OS_NAME" = "darwin" ]; then
    warn "No conda/venv detected on macOS; falling back to system python"
  fi

  echo "python"
}

install_system_pkg() {
  pkg="$1"

  if command -v brew >/dev/null 2>&1; then
    brew install "$pkg"
    return
  fi

  if command -v apt-get >/dev/null 2>&1; then
    apt-get update && apt-get install -y "$pkg"
    return
  fi

  if command -v dnf >/dev/null 2>&1; then
    dnf install -y "$pkg"
    return
  fi

  if command -v yum >/dev/null 2>&1; then
    yum install -y "$pkg"
    return
  fi

  if command -v winget >/dev/null 2>&1; then
    winget install --id "$pkg" -e
    return
  fi

  if command -v choco >/dev/null 2>&1; then
    choco install -y "$pkg"
    return
  fi

  warn "No supported system package manager found for $pkg"
  return 1
}

FAIL=0

# --- Dependency: <name> (<type>) ---
if <checkCommand> >/dev/null 2>&1; then
  log "<name>: present"
else
  log "<name>: missing, installing..."
  <installCommand> || { warn "Failed to install <name>"; FAIL=$((FAIL+1)); }
fi

# ... repeat for each dependency ...

if [ "$FAIL" -gt 0 ]; then
  warn "$FAIL dependencies failed to install"
  exit 1
fi

log "All dependencies satisfied"
